# Generated by Django 5.2.7 on 2025-10-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='credito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='core.creditocarbono'),
        ),
        migrations.AlterField(
            model_name='creditocarbono',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Vendido', 'Vendido'), ('Listado', 'Listado')], default='Aprovado', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Vendido', 'Vendido'), ('Listado', 'Listado')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='usuario_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_enviadas', to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(limit_choices_to={'tipo': 'Empresa Compradora'}, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='core.usuario')),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='core.creditocarbono')),
                ('vendedor', models.ForeignKey(limit_choices_to={'tipo': 'Produtor Rural'}, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='core.usuario')),
            ],
        ),
    ]
