# Generated by Django 5.2.7 on 2025-10-31 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requisicao_credito_alter_creditocarbono_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('Aprovar', 'Aprovar'), ('Rejeitar', 'Rejeitar'), ('Comentar', 'Comentar')], max_length=50)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(limit_choices_to={'tipo': 'Administrador'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.requisicao')),
            ],
        ),
    ]
