# Generated by Django 5.2.7 on 2025-10-30 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Administrador', 'Administrador'), ('Produtor Rural', 'Produtor Rural'), ('Empresa Compradora', 'Empresa Compradora')], max_length=50)),
                ('saldo_creditos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_requisicao', models.CharField(choices=[('Registro', 'Registro de Créditos'), ('Venda', 'Venda de Créditos'), ('Compra', 'Compra de Créditos')], max_length=50)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('preco_un', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('origem_credito', models.CharField(blank=True, max_length=255, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Vendido', 'Vendido')], default='Pendente', max_length=50)),
                ('usuario_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CreditoCarbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('preco_un', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Pendente', 'Pendente'), ('Rejeitado', 'Rejeitado'), ('Vendido', 'Vendido')], default='Aprovado', max_length=50)),
                ('produtor', models.ForeignKey(limit_choices_to={'tipo': 'Produtor Rural'}, on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
